services:
  blog:
    image: nginx:alpine
    container_name: blog
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
